import json
import os
import re
from typing import Any

from .llm.factory import create_provider, get_provider_config
from .prompts import SYSTEM_PROMPT, build_user_prompt
from .schema_reader import column_names, find_table, numeric_columns


def generate_sql(question: str, schema: dict[str, Any], safety_rules: list[str]) -> dict[str, Any]:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_user_prompt(question, schema, safety_rules)},
    ]
    try:
        config = get_provider_config()
        provider = create_provider(config)
        content = provider.generate(messages, temperature=config.temperature)
        return normalize_generation(parse_model_json(content))
    except Exception:
        if mock_enabled():
            return mock_generate(question, schema)
        raise


def parse_model_json(content: str) -> dict[str, Any]:
    text = content.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    extracted = extract_first_json_object(text)
    if extracted is None:
        raise ValueError("LLM response did not contain valid JSON")
    try:
        return json.loads(extracted)
    except json.JSONDecodeError as exc:
        raise ValueError("LLM response contained malformed JSON") from exc


def extract_first_json_object(text: str) -> str | None:
    start = text.find("{")
    if start == -1:
        return None

    depth = 0
    in_string = False
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start : index + 1]
    return None


def normalize_generation(data: dict[str, Any]) -> dict[str, Any]:
    sql = str(data.get("sql", "")).strip()
    explanation = str(data.get("explanation", "")).strip()
    try:
        confidence = float(data.get("confidence", 0.0))
    except (TypeError, ValueError):
        confidence = 0.0

    if not sql:
        raise ValueError("LLM JSON response did not include sql")
    if not explanation:
        explanation = "Generated by configured LLM provider."

    return {
        "sql": sql,
        "explanation": explanation,
        "confidence": max(0.0, min(confidence, 1.0)),
    }


def mock_enabled() -> bool:
    return os.getenv("ENABLE_MOCK_LLM", "").strip().lower() in {"1", "true", "yes", "on"}


def mock_generate(question: str, schema: dict[str, Any]) -> dict[str, Any]:
    join_sql = mock_revenue_join(question, schema)
    if join_sql:
        return join_sql

    table = find_table(schema, question)
    if not table:
        return {
            "sql": "SELECT 1 AS value LIMIT 100",
            "explanation": "No tables were available, so the mock generator returned a trivial read-only query.",
            "confidence": 0.2,
        }

    q = question.lower()
    table_name = quote_ident(table["name"])
    cols = column_names(table)
    selected = ", ".join(quote_ident(c) for c in cols[:6]) or "*"
    limit = extract_limit(q) or 100

    if ("count" in q or "how many" in q) and cols:
        return {
            "sql": f"SELECT COUNT(*) AS count FROM {table_name} LIMIT 100",
            "explanation": f"Mock generator detected a count question for {table['name']}.",
            "confidence": 0.66,
        }

    nums = numeric_columns(table)
    if any(term in q for term in ("top", "highest", "largest", "most", "total", "revenue", "sum")) and nums:
        metric = choose_metric(nums, q)
        label_cols = [c for c in cols if c != metric][:2]
        group_cols = ", ".join(quote_ident(c) for c in label_cols)
        select_cols = (group_cols + ", ") if group_cols else ""
        group_clause = f" GROUP BY {group_cols}" if group_cols else ""
        return {
            "sql": f"SELECT {select_cols}SUM({quote_ident(metric)}) AS total_{metric} FROM {table_name}{group_clause} ORDER BY total_{metric} DESC LIMIT {min(limit, 100)}",
            "explanation": f"Mock generator selected numeric column {metric} and sorted totals descending.",
            "confidence": 0.58,
        }

    where = ""
    for col in cols:
        if col.lower() in q and any(word in q for word in ("where", "with", "named", "email")):
            match = re.search(rf"{re.escape(col.lower())}\s+(?:is|=|contains)\s+['\"]?([\w@.\-]+)", q)
            if match:
                where = f" WHERE {quote_ident(col)} LIKE '%{escape_literal(match.group(1))}%'"
                break

    return {
        "sql": f"SELECT {selected} FROM {table_name}{where} LIMIT {min(limit, 100)}",
        "explanation": f"Mock generator chose table {table['name']} based on the question and schema.",
        "confidence": 0.52,
    }


def mock_revenue_join(question: str, schema: dict[str, Any]) -> dict[str, Any] | None:
    q = question.lower()
    if not any(term in q for term in ("revenue", "sales", "total")):
        return None
    tables = {table["name"].lower(): table for table in schema.get("tables", [])}
    limit = extract_limit(q) or 10
    if {"customers", "orders", "order_items"}.issubset(tables) and "customer" in q:
        return {
            "sql": (
                'SELECT "customers"."id", "customers"."name", SUM("order_items"."line_total") AS total_revenue '
                'FROM "customers" '
                'JOIN "orders" ON "orders"."customer_id" = "customers"."id" '
                'JOIN "order_items" ON "order_items"."order_id" = "orders"."id" '
                'GROUP BY "customers"."id", "customers"."name" '
                f"ORDER BY total_revenue DESC LIMIT {min(limit, 100)}"
            ),
            "explanation": "Mock generator recognized a customer revenue ranking and joined customers, orders, and order_items.",
            "confidence": 0.74,
        }
    if {"products", "order_items"}.issubset(tables) and "product" in q:
        return {
            "sql": (
                'SELECT "products"."id", "products"."name", SUM("order_items"."line_total") AS total_revenue '
                'FROM "products" '
                'JOIN "order_items" ON "order_items"."product_id" = "products"."id" '
                'GROUP BY "products"."id", "products"."name" '
                f"ORDER BY total_revenue DESC LIMIT {min(limit, 100)}"
            ),
            "explanation": "Mock generator recognized a product revenue ranking and joined products with order_items.",
            "confidence": 0.74,
        }
    return None


def quote_ident(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def escape_literal(value: str) -> str:
    return value.replace("'", "''")


def extract_limit(question: str) -> int | None:
    match = re.search(r"\b(?:top|limit|first)\s+(\d{1,3})\b", question)
    if not match:
        return None
    return max(1, min(int(match.group(1)), 100))


def choose_metric(columns: list[str], question: str) -> str:
    for preferred in ("revenue", "total", "amount", "price", "quantity", "count"):
        for column in columns:
            if preferred in column.lower() and (preferred in question or preferred in ("amount", "price")):
                return column
    return columns[0]
